### ISSUE TITLE
Swift stdlib tool throws a warning while processing ZendeskSDKStrings.bundle

### ISSUE THREAD

**Issue by jeffremer** [zendesk/zendesk_sdk_ios#382]
I'm observing a warning coming from build step where `builtin-swiftStdLibTool` scans and signs binaries. I'm fairly certain I have things set up according to the integration instructions.

[Here's a sample project](https://github.com/jeffremer/ZendeskWarning) showing the warning.

- SDK version: 2.0.2
- Xcode version: 9.3
- iOS or Simulator: iPhone X device and any iPhone simulator
- iOS Version: 11.3
- Swift version: 4.1

Steps to Reproduce:

1. Include the Zendesk 2.0.2 SDK according to instructions
2. Build
3. Observe the warning…

```
:  /Users/jeff/Library/Developer/Xcode/DerivedData/ZendeskWarning-drpgigctungzqobtzmvurywdjqbc/Build/Products/Debug-iphonesimulator/ZendeskWarning.app/Frameworks/ZendeskProviderSDK.framework/ZendeskSDKStrings.bundle/_CodeSignature/CodeSignature: Failed to parse Mach-O: Reached end of file while looking for: uint32_t.
```

<img width="1392" alt="screen shot 2018-05-09 at 12 11 46 pm" src="https://user-images.githubusercontent.com/99528/39834545-2ccbab1a-5382-11e8-8566-1ed95371c492.png">

[Build target ZendeskWarning_2018-05-09T12-10-18.log.rtf.zip](https://github.com/zendesk/zendesk_sdk_ios/files/1989173/Build.target.ZendeskWarning_2018-05-09T12-10-18.log.rtf.zip)

**Comment by divo** [comment]
@jeffremer we released 2.0.3 yesterday, it does not emit this warning.

I don't know what caused it or what fixed it. It _looks_ like it's due to something in the toolchain, not the SDK. It does seem harmless and it's no longer an issue so I'm going to close this.

Thank you for reporting this and taking the time to create a project that reproduces the issue. It was very helpful in verifying 2.0.3

**Comment by jeffremer** [comment]
No update on this? I tried just manually deleting the `_CodeSignature` directory under `ZendeskProviderSDK.framework/ZendeskSDKStrings.bundle/` which resolves the warning. I was able to archive and validate it, so hopefully that's just safe to do.

**Comment by rainypixels** [comment]
I'm still seeing it as well...

**Comment by KillianSmith0** [comment]
Can you's update to 2.0.5 and see if the issue persists? I wasn't able to replicate, thanks

**Comment by jeffremer** [comment]
This still happens with 2.0.5.

<img width="616" alt="screen shot 2018-07-10 at 8 41 23 pm" src="https://user-images.githubusercontent.com/99528/42549585-c23bf166-8481-11e8-89c7-3ca5a6d724c1.png">

**Comment by jeffremer** [comment]
This still happens in 2.1.0 @KillianSmith0. The `_CodeSignature` directory in `ZendeskSDKStrings.bundle` appears unnecessary and I have to delete it manually every time I update the SDK.

**Comment by agordeev** [comment]
I experience this on `2.1.1`. @divo can we reopen the issue to not to create a new one?
