### ISSUE TITLE
Text view in request view is hidden in iPad with using external keyboard

### ISSUE THREAD

**Issue by pixyzehn** [zendesk/zendesk_sdk_ios#445]
- SDK version 2.1.0:
- Xcode version 10:
- iOS or Simulator iOS:
- iOS Version 12:
- Swift version 4.1:

Steps to Reproduce:

1. Open a request view composed by `RequestUi.buildRequestUi` with using external keyboard in iPad.
2. The text view in the request view is hidden.

Result: The text view shouldn't be hidden.

<img src="https://user-images.githubusercontent.com/2482478/46365961-d7dd2a80-c671-11e8-8613-bd66fb4ac62d.jpeg" width="640">

I guess the calculation of the text view's position based on the keyboard is something wrong if there is no keyboard.

Also, I can see some UI issue if I just use the internal keyboard in iPad.

<img src="https://user-images.githubusercontent.com/2482478/46366152-53d77280-c672-11e8-8468-3df1fce4d847.PNG" width="640">

**Comment by KillianSmith0** [comment]
Hi @pixyzehn, unfortunately I was also able to replicate this.. Thanks for reporting this, I will log an issue in our backlog to address it, and keep you posted on this issue

**Comment by KillianSmith0** [comment]
Hey @pixyzehn,
This issue should be fixed when you update to our latest release `v2.3`.. I will close this issue for now, feel free to open another if you have any other problems!

**Comment by pixyzehn** [comment]
@KillianSmith0 I tested it with the latest release which is `v2.3`, but on `iPad Pro (10.5-inch) - 12.1`, the text view will be hidden by the keyboard. Could you check it? If it's an issue, please reopen the issue.

<img src="https://user-images.githubusercontent.com/2482478/48547741-3af1ec00-e8c3-11e8-883a-50fe6b03da0b.png" width="640">

**Comment by KillianSmith0** [comment]
> The text view in the request view is hidden.
By text view, do you mean the input field (Attacment/texfield/send)? 

Ok, we'll have to look further into this! Can you confirm the issue with internal keyboard still persists? Or is it just when external keyboard is connected? Thanks

**Comment by pixyzehn** [comment]
@KillianSmith0 If it's with an external keyboard, it's no problem. The keyboard show properly.
The issue still persists only with an internal keyboard as I showed you in the screenshot.

**Comment by baz8080** [comment]
@pixyzehn thanks for the info. We'll discuss the bug internally.

**Comment by kurtguenther** [comment]
I can also confirm that `2.3` fixes the external hardware keyboard UI problems. But the normal (non-hardware) keyboard UI problems are still in `2.3`

**Comment by KillianSmith0** [comment]
@kurtguenther, @pixyzehn 

We currently have a fix for the layout issue where the keyboard blocks the inputField. It will be included in our next version release. However we still have issues with the extra padding of the inputField in your second image. As it's not a feature bug, it won't be prioritised as highly as other tasks, so we can't guarantee it will definitely be in the next release. 

We'll keep you posted on the status closer to a release..

Regards,
Killian

**Comment by SL62** [comment]
Hi @KillianSmith0 

We're seeing a similar keyboard / input field issue on physical devices. Here's an example of it happening on an iPhone 6S:
<img width="549" alt="Zendesk_Keyboard_Input_Issue" src="https://user-images.githubusercontent.com/26548656/55470900-7b4ad000-5600-11e9-84c0-aba0db3109b7.png">

We've had several reports of this from users and were wondering if you had any update on this?

SDK version 2.3.0:
Xcode version 10.1:
iOS Physical Device:
iOS Version 12.1.4:
Swift version 4:

Many thanks
